name: Build Multi-Arch Image

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        platform: [linux/amd64, linux/arm64]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}

      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          image: ghcr.io/${{ github.repository }}:${{ matrix.arch }}
          only-severities: critical,high
